version: '2'

services:
    node:
        env_file: .docker.env
        build: .
        links:
            - redis
        ports:
            - "8080:8080"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - data_storage:/data
        command: redis-server --appendonly yes

volumes:
    data_storage:
