version: '2'

services:
    node:
        env_file: .docker.env
        build: .
        links: 
            - redis
        ports:
            - "8080:8080"
        
    redis:
        image: redis
        ports:
            - "6379:6379"